export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_UNAUTHORIZED: "INTERNAL_UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  COMPANION_PROFILE_NOT_FOUND: "COMPANION_PROFILE_NOT_FOUND",
  INVALID_LANGUAGE: "INVALID_LANGUAGE",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  VENUE_NOT_FOUND: "VENUE_NOT_FOUND",
  COMPANION_NOT_FOUND: "COMPANION_NOT_FOUND",
  NO_DUO_AVAILABLE: "NO_DUO_AVAILABLE",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  CLIENT_ALREADY_HAS_NON_TERMINAL_BOOKING: "CLIENT_ALREADY_HAS_NON_TERMINAL_BOOKING",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  COMPANION_NOT_ASSIGNED: "COMPANION_NOT_ASSIGNED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
